//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTHL2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewTHL2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PBG {
            get {
                object obj = ResourceManager.GetObject("PBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   [FilePath]
        ///Th06 =
        ///Th07 =
        ///Th075 
        ///Th08 =
        ///Th09 =
        ///Th095 =
        ///Th10 =
        ///Th105 =
        ///Th11 =
        ///Th12 =
        ///Th123 =
        ///Th125 =
        ///Th128 =
        ///Th13 =
        ///Th135 =
        ///Th14 =
        ///Th143
        ///alcostg =
        ///[Vsync]
        ///Th06 =
        ///Th07 = 
        ///Th08 = 
        ///Th09 = 
        ///Th095 = 
        ///Th10 = 
        ///Th11 = 
        ///Th12 = 
        ///Th125 = 
        ///Th128 = 
        ///Th13 = 
        ///alcostg = 
        ///[BG]
        ///Th06 = 
        ///Th07 = 
        ///Th075 = 
        ///Th08 = 
        ///Th09 = 
        ///Th095 = 
        ///Th10 = 
        ///Th105 = 
        ///Th11 = 
        ///Th12 = 
        ///Th123 = 
        ///Th125 = 
        ///Th128 = 
        ///Th13 = 
        ///Th135 = 
        ///Th14 = 
        ///Th143 =
        ///alcostg =
        ///
        //////Backup///
        ///	[TH06BU]
        ///	Save =
        ///    Replay =        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setteingTemplate {
            get {
                return ResourceManager.GetString("setteingTemplate", resourceCulture);
            }
        }
    }
}
