//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTHL2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewTHL2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [HASH]
        ///alcostg = b31eb1628c8478b24a1b628a4f1ebc11
        ///th06 = fa3d64768b1bfc50703dedc2db92f7fa
        ///th07 = 0126afce1e805370d36c3482445e98da
        ///th075 = 21bcb855a39f2170195811e6ad292f18
        ///th08 = 77b6785e04a3406e50be68714a193650
        ///th09 = 8bc284d591e247cb62fe62a710ac1689_cf634df46e05552e104fa97a971aaac0
        ///th095 = 8de95bc7651419201fc1a4ea49bc0697
        ///th10 = 7dc488d82c81dd4aee4ba098b8804d83
        ///th105 = 2ae711a6c92c4addbdbf526bc61d8e59
        ///th11 = 6af1e3b37f28293f4fc127ee01d2632c
        ///th12 = 212f187591f4f1fa99eb2845d1b3cf20
        ///th123 = df35d1 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string hash {
            get {
                return ResourceManager.GetString("hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap me {
            get {
                object obj = ResourceManager.GetObject("me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PBG {
            get {
                object obj = ResourceManager.GetObject("PBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   [FilePath]
        ///Th06 =
        ///Th07 =
        ///Th075 =
        ///Th08 =
        ///Th09 =
        ///Th095 =
        ///Th10 =
        ///Th105 =
        ///Th11 =
        ///Th12 =
        ///Th123 =
        ///Th125 =
        ///Th128 =
        ///Th13 =
        ///Th135 =
        ///Th14 =
        ///Th143
        ///alcostg =
        ///[Vsync]
        ///Th06 =
        ///Th07 = 
        ///Th08 = 
        ///Th09 = 
        ///Th095 = 
        ///Th10 = 
        ///Th11 = 
        ///Th12 = 
        ///Th125 = 
        ///Th128 = 
        ///Th13 = 
        ///alcostg = 
        ///[BG]
        ///Th06 = 
        ///Th07 = 
        ///Th075 = 
        ///Th08 = 
        ///Th09 = 
        ///Th095 = 
        ///Th10 = 
        ///Th105 = 
        ///Th11 = 
        ///Th12 = 
        ///Th123 = 
        ///Th125 = 
        ///Th128 = 
        ///Th13 = 
        ///Th135 = 
        ///Th14 = 
        ///Th143 =
        ///alcostg =
        ///
        //////Backup///
        ///[TH06BU]
        ///Save =
        ///Replay =
        ///Vpat [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setteingTemplate {
            get {
                return ResourceManager.GetString("setteingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap spana {
            get {
                object obj = ResourceManager.GetObject("spana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap spana_32 {
            get {
                object obj = ResourceManager.GetObject("spana_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap spana_click {
            get {
                object obj = ResourceManager.GetObject("spana_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   [Window]
        ///AskWindowMode = 0
        ///enabled = 1
        ///X = 0
        ///Y = 0
        ///Width = 1280
        ///Height = 728
        ///TitleBar = 0
        ///AlwaysOnTop = 0
        ///
        ///[Option]
        ///Vsync = 0
        ///SleepType = 1
        ///BltPrepareTime = -1
        ///AutoBltPrepareTime = 1
        ///AllowShortDelay = 0
        ///GameFPS = 60
        ///ReplaySkipFPS = 200
        ///ReplaySlowFPS = 30
        ///CalcFPS = 1
        ///BugFixGetDeviceState = 0
        ///BugFixCherry = 0
        ///BugFixTh10Power3 =0
        ///BugFixTh12Shadow = 0
        ///DisableChecksum = 0
        ///AllowShortDelay = 0
        ///AlwaysBlt = 1
        ///ProcessPriority = 0
        ///ProcessAffinityMask = 0
        ///LockBackBuffer = 0
        ///D3DMultiThread  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vpatch_All {
            get {
                return ResourceManager.GetString("vpatch_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Window]
        ///AskWindowMode = 0
        ///enabled = 1
        ///X = 0
        ///Y = 0
        ///Width = 1024
        ///Height = 768
        ///TitleBar = 1
        ///AlwaysOnTop = 1
        ///
        ///[Option]
        ///Vsync = 0
        ///SleepType = 1
        ///BltPrepareTime = 0
        ///AutoBltPrepareTime = -1
        ///AllowShortDelay = 0
        ///GameFPS = 60
        ///ReplaySkipFPS = 200
        ///ReplaySlowFPS = 30
        ///CalcFPS = 1
        ///AlwaysBlt = 0
        ///BugFixGetDeviceState = 0
        ///BugFixCherry = 0
        ///BugFixTh10Power3 =0
        ///BugFixTh12Shadow = 0
        ///ProcessPriority = 0
        ///ProcessAffinityMask = 0
        ///LockBackBuffer = 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vpatch_th06_th11 {
            get {
                return ResourceManager.GetString("vpatch_th06_th11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Window]
        ///AskWindowMode = 0
        ///enabled = 0
        ///X = 0
        ///Y = 0
        ///Width = 640
        ///Height = 480
        ///TitleBar = 0
        ///AlwaysOnTop = 0
        ///
        ///[Option]
        ///Vsync = 0
        ///SleepType = 1
        ///BltPrepareTime = 4
        ///AutoBltPrepareTime = 1
        ///AllowShortDelay = 0
        ///GameFPS = 60
        ///ReplaySkipFPS = 240
        ///ReplaySlowFPS = 30
        ///AlwaysBlt = 0
        ///CalcFPS = 1
        ///BugFixTh12Shadow = 0
        ///ProcessPriority = 0
        ///ProcessAffinityMask = 0
        ///LockBackBuffer = 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vpatch_th12 {
            get {
                return ResourceManager.GetString("vpatch_th12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Window]
        ///AskWindowMode = 0
        ///enabled = 1
        ///X = 0
        ///Y = 0
        ///Width = 1024
        ///Height = 768
        ///TitleBar = 1
        ///AlwaysOnTop = 1
        ///
        ///[Option]
        ///Vsync = 0
        ///SleepType = 1
        ///BltPrepareTime = 0
        ///AutoBltPrepareTime = -1
        ///AllowShortDelay = 0
        ///GameFPS = 60
        ///ReplaySkipFPS = 200
        ///ReplaySlowFPS = 30
        ///CalcFPS = 1
        ///AlwaysBlt = 0
        ///BugFixGetDeviceState = 0
        ///ProcessPriority = 0
        ///ProcessAffinityMask = 0
        ///LockBackBuffer = 0
        ///D3DMultiThread = 0
        ///HookDirectInput = 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vpatch_th125 {
            get {
                return ResourceManager.GetString("vpatch_th125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Window]
        ///AskWindowMode = 0
        ///enabled = 1
        ///X = 0
        ///Y = 0
        ///Width = 1280
        ///Height = 728
        ///TitleBar = 0
        ///AlwaysOnTop = 0
        ///
        ///[Option]
        ///Vsync = 0
        ///SleepType = 1
        ///BltPrepareTime = -1
        ///AutoBltPrepareTime = 1
        ///AllowShortDelay = 0
        ///GameFPS = 60
        ///ReplaySkipFPS = 200
        ///ReplaySlowFPS = 30
        ///CalcFPS = 1
        ///AllowShortDelay = 0
        ///AlwaysBlt = 1
        ///ProcessPriority = 0
        ///ProcessAffinityMask = 0
        ///LockBackBuffer = 0
        ///D3DMultiThread = 0
        ///MagnificationMethod = 0
        ///DisableChecksum = 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vpatch_th13 {
            get {
                return ResourceManager.GetString("vpatch_th13", resourceCulture);
            }
        }
    }
}
